### ISSUE TITLE
Error in trying to run PICALO

### ISSUE THREAD

**Issue by mariesaitou** [molgenis/PICALO#5]
Hi, I hope all is well.
I am trying to run PICALO but get the following error.
Do you have a working example dataset so that I can investigate what is wrong with my dataset?
Also, please let me know if you guess there is something wrong other than the data.

Best,
Marie 

-------

(picalo) (base) [mariesai@login PICALO]$ ./picalo.py -eq ../PICALO_cis_eQTL_uniqSNP.txt -ge ../PICALOsnp.txt -ex ../PICALO_expression.tsv -co  ../covariate_synchro_guess.txt -tc ../covariate_synchro_tech.txt
Input argument 'eqtl' has value '../PICALO_cis_eQTL_uniqSNP.txt'.
Input argument 'genotype' has value '../PICALOsnp.txt'.
Input argument 'genotype_na' has value '-1'.
Input argument 'expression' has value '../PICALO_expression.tsv'.
Input argument 'tech_covariate' has value '../covariate_synchro_tech.txt'.
Input argument 'tech_covariate_with_inter' has value 'None'.
Input argument 'covariate' has value '../covariate_synchro_guess.txt'.
Input argument 'sample_to_dataset' has value 'None'.
Input argument 'min_dataset_size' has value '30'.
Input argument 'eqtl_alpha' has value '0.05'.
Input argument 'call_rate' has value '0.95'.
Input argument 'hardy_weinberg_pvalue' has value '0.0001'.
Input argument 'minor_allele_frequency' has value '0.01'.
Input argument 'min_group_size' has value '2'.
Input argument 'ieqtl_alpha' has value '0.05'.
Input argument 'n_components' has value '10'.
Input argument 'min_iter' has value '5'.
Input argument 'max_iter' has value '100'.
Input argument 'tol' has value '0.001'.
Input argument 'force_continue' has value 'False'.
Input argument 'outdir' has value 'output'.
Input argument 'verbose' has value 'False'.
13:42:14  [INFO]  Arguments:
13:42:14  [INFO]    > Logfile: /net/fs-2/scale/OrionStore/Projects/MSLab/Marie/2022_Synchrosmolt/QTLTools/PICALO/output/output/log.log
13:42:14  [INFO]    > Verbose: False
13:42:14  [INFO]    > Level: INFO
13:42:14  [INFO]  
13:42:14  [INFO]  Data Arguments:
13:42:14  [INFO]    > eQTL input path: ../PICALO_cis_eQTL_uniqSNP.txt
13:42:14  [INFO]    > Genotype input path: ../PICALOsnp.txt
13:42:14  [INFO]    > Expression input path: ../PICALO_expression.tsv
13:42:14  [INFO]    > Technical covariates input path: ../covariate_synchro_tech.txt
13:42:14  [INFO]    > Technical covariates with interaction input path: None
13:42:14  [INFO]    > Covariates input path: ../covariate_synchro_guess.txt
13:42:14  [INFO]    > Sample-dataset path: None
13:42:14  [INFO]  
13:42:14  [INFO]  Starting program
13:42:14  [INFO]  Arguments:
13:42:14  [INFO]    > Genotype NA value: -1
13:42:14  [INFO]    > Minimal dataset size: >=30
13:42:14  [INFO]    > eQTL alpha: <=0.05
13:42:14  [INFO]    > SNP call rate: >0.95
13:42:14  [INFO]    > Hardy-Weinberg p-value: >=0.0001
13:42:14  [INFO]    > MAF: >0.01
13:42:14  [INFO]    > Minimal group size: >=2
13:42:14  [INFO]    > ieQTL alpha: <=0.05
13:42:14  [INFO]    > N components: 10
13:42:14  [INFO]    > Minimal iterations: 5
13:42:14  [INFO]    > Maximum iterations: 100
13:42:14  [INFO]    > Tolerance: 0.001
13:42:14  [INFO]    > Force continue: False
13:42:14  [INFO]    > Output directory: /net/fs-2/scale/OrionStore/Projects/MSLab/Marie/2022_Synchrosmolt/QTLTools/PICALO/output/output
13:42:14  [INFO]  
13:42:14  [INFO]  Loading eQTL data and filter on FDR values of the main eQTL effect
13:42:14  [INFO]  	Loaded dataframe: PICALO_cis_eQTL_uniqSNP.txt with shape: (4480, 4)
Traceback (most recent call last):
  File "/net/fs-2/scale/OrionStore/Projects/MSLab/Marie/2022_Synchrosmolt/QTLTools/picalo/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'FDR'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./picalo.py", line 111, in <module>
    PROGRAM.start()
  File "/net/fs-2/scale/OrionStore/Projects/MSLab/Marie/2022_Synchrosmolt/QTLTools/PICALO/src/main.py", line 94, in start
    eqtl_fdr_keep_mask = (eqtl_df["FDR"] <= self.eqtl_alpha).to_numpy(dtype=bool)
  File "/net/fs-2/scale/OrionStore/Projects/MSLab/Marie/2022_Synchrosmolt/QTLTools/picalo/lib/python3.7/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/net/fs-2/scale/OrionStore/Projects/MSLab/Marie/2022_Synchrosmolt/QTLTools/picalo/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'FDR'

**Comment by mvochteloo** [comment]
Hi Marie,

PICALO expected three columns in the eQTL input data: _FDR_ (eQTL FDR), _SNPName_ (the eQTL SNP), and _ProbeName_ (the eQTL gene). Your data file is missing the _FDR_ column. This column was by accident described as _Pvalue_ in the README, apologies for the inconvenience. 

Since this column is practically unused in the current version of PICALO, I have removed it and updated the documentation accordingly.

Best,
Martijn
